export const ABAP_VALUE_STATE = {
  SUCESS: "3",
  ERROR: "1",
  WARNING: "2",
  INFORMATION_NEW: "5",
  INFORMATION_OLD: "0",
};
export const ABAP_VALUE_STATE_NUMBER = {
  SUCESS: 3,
  ERROR: 1,
  WARNING: 2,
  INFORMATION_NEW: 5,
  INFORMATION_OLD: 0,
};
